type IEnv = {
  VITE_HOST_APP_BE_HOST: string
  VITE_HOST_APP_SOCKET_HOST: string
  VITE_HOST_IMAGE_HOST: string
  VITE_HOST_DOMAIN: string
  VITE_HOST_CDN: string
  VITE_HOST_ID_WIDGET: string
  VITE_HOST_DOMAIN_TRIGGER_BTN: string
  VITE_HOST_APP_URL: string
  VITE_HOST_WIDGET_URL: string
  VITE_HOST_CHATBOT_URL: string
  VITE_HOST_APP_V2_URL: string
  VITE_ENDPOINT_READ_MESSAGE: string
  VITE_ENDPOINT_SEND_MESSAGE: string
  VITE_ENDPOINT_INIT_CLIENT: string
  VITE_ENDPOINT_READ_PAGE_INFO: string
  VITE_ENDPOINT_CLIENT_INFO: string
}
